[package]
name = "block"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.21.3", features = ["persistence"] }
egui_node_graph = { version = "0.4.0", features = ["serde", "persistence"] }
